### ISSUE TITLE
Small css change request

### ISSUE THREAD

**Issue by Simonh2o** [swing-opensource/swingmusic#206]
Could you change the background color of the div **'now-playing-track-indicator'** to #fefefe from #ffffffde? Currently it doesn't have the same color as the now-playing-indicator gif and looks clipped into place.
![Screenshot 2024-04-08 041826](https://github.com/swing-opensource/swingmusic/assets/44584359/739449e7-7388-42de-8b54-2bd6f7c16fd5)

**Comment by cwilvx** [comment]
@Simonh2o 

Thanks for the heads up. I'll fix that.

Thank you v much.

**Comment by Simonh2o** [comment]
The gif and background seem to have the same color when the song is paused, to light grey instead of white.
![image](https://github.com/swing-opensource/swingmusic/assets/44584359/7b78eb5e-5595-4bf1-8de5-be895199d0fc)

**Comment by Simonh2o** [comment]
It would also be nice if the song you're currently listening to was in the page title, instead of showing the current page you're on?
![image](https://github.com/swing-opensource/swingmusic/assets/44584359/682de2a1-14c5-4470-a8c9-788903ec50f4)
I see an argument for both, maybe it could be changed by a toggle in settings.

**Comment by Simonh2o** [comment]
Some additional changes/improvements (in my opinion):

1. Change div **'.b-bar .center .time span'** to prevent bg(the div) from moving when the numbers change, also padding for 
    improved spacing:
    font-variant-numeric: tabular-nums;
    padding: 1px 4px;
    old:
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/c0c1e6e5-6b42-434c-9b38-34c7bf12d9f3)
    new:
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/fa7d4e63-864d-44a5-bea9-3405fde218b7)

3. Tooltip on timeline hover with exact time:
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/4c0c2345-2d5a-417d-967b-83a96896eac7)

4. More compact volume area with exact volume level tooltip:
    **'dialog rounded-sm pad-sm'**
    bottom: 50px;
    padding: 0 12px;
    height: 34px;
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/6b2cc86b-c7bb-4249-abdb-36b185b57d97)
    Vertical sketch:    
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/5545a762-de62-43d8-a03f-97c47ca30c87)

5. Maybe increase the flex gap between cover and text a bit more (for more breathing room), from 8px to 10px or even 12px?
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/de82ddf6-dfe3-4316-972b-c901cde9cac2)

6. Move the main buttons higher up and away from the bottom of the page?
    old:
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/152c68e5-37fe-4177-b256-5775bc42edee)
    new:    
    ![image](https://github.com/swing-opensource/swingmusic/assets/44584359/e222805f-df79-4389-a0bc-98c90c860901)

I also find the scrollbar to be quite small and sometimes hard to grab (would be cool if the webkit scrollbars were only changed for windows/chrome (I feel like it impacts scroll performance on android/mac on chrome).
![image](https://github.com/swing-opensource/swingmusic/assets/44584359/e0774eee-a26e-4ff8-bbc0-b40e9d9d3edb)
Thoughts on this one? https://codepen.io/Spemer/pen/baoKPK

**Comment by cwilvx** [comment]
Hi @Simonh2o 

Thanks for the good suggestions. Please keep them coming! We appreciate your contributions and we'll use them to improve your experience in future releases.

##
The codepen looks great. I think it would be a great replacement for the current webkit scrollbar.

_PS: If you'd like to implement the suggestions here or others, feel free to open a PR on the [webclient repo](https://github.com/swing-opensource/webclient) or drop me a message on Telegram if you have any questions or just wanna chat. I reply swiftly. Thank you._

**Comment by Simonh2o** [comment]
Sadly don't use telegram at all, and it's not feasible to sign up with a temp number. I tried cloning the webclient repo before but couldn't get it started (lots of errors), assuming you also require the backend? I will try again.

**Comment by Simonh2o** [comment]
It's starting up without issues now, but stuck at selecting directory path, so not getting anywhere.
![image](https://github.com/swing-opensource/swingmusic/assets/44584359/2f7d9941-3150-4eca-b510-992fbf6aa123)
![image](https://github.com/swing-opensource/swingmusic/assets/44584359/a4e0dd32-51d7-4621-a12e-6a3f1217d85a)

**Comment by cwilvx** [comment]
Hi @Simonh2o 

I've seen the root dir problem on my local build, looks like a problem with the backend. I'll fix that and get back to you.

---

How do you feel about Discord? I can setup a room there if you are ok with it

**Comment by cwilvx** [comment]
@Simonh2o 

The root dir problem has been fixed by the latest commit on the web client repo. Just git pull that repo and rerun `yarn dev`

**Comment by Simonh2o** [comment]
Still broken on windows btw, can't browse to local folder (different drive)

**Comment by cwilvx** [comment]
@Simonh2o 

https://discord.com/invite/CV7zYqmY
